# Generated by Django 5.2.11 on 2026-03-13 07:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_contactenquiry_sitepage_sitepagesection_wishlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatbotQA',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=500)),
                ('answer', models.TextField()),
                ('category', models.CharField(blank=True, default='general', help_text='Category for grouping (e.g. booking, general, payment)', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('ordering', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Chatbot Q&A',
                'verbose_name_plural': 'Chatbot Q&As',
                'ordering': ['ordering', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('platform', models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('twitter', 'Twitter / X'), ('youtube', 'YouTube'), ('tiktok', 'TikTok'), ('linkedin', 'LinkedIn'), ('whatsapp', 'WhatsApp'), ('viber', 'Viber'), ('other', 'Other')], max_length=20)),
                ('url', models.URLField(max_length=500)),
                ('label', models.CharField(blank=True, default='', help_text='Display label (optional, defaults to platform name)', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('ordering', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['ordering', 'created_at'],
            },
        ),
    ]
