# Generated by Django 5.2.11 on 2026-03-13 00:00

import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_chatbotqa_sociallink"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatbotUserQuery",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("question", models.TextField(max_length=1200)),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "Pending"), ("replied", "Replied"), ("closed", "Closed")],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("admin_reply", models.TextField(blank=True, default="")),
                ("replied_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=models.deletion.CASCADE,
                        related_name="chatbot_queries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Chatbot User Query",
                "verbose_name_plural": "Chatbot User Queries",
                "ordering": ["-created_at"],
            },
        ),
    ]
