# Generated by Django 5.2.11 on 2026-03-13 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_chatbotuserquery'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbotuserquery',
            name='reply_seen',
            field=models.BooleanField(default=False, help_text='Whether the user has seen the admin reply'),
        ),
    ]
